# H2 Database for Testing
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true

# Dummy OAuth2 for tests
spring.security.oauth2.client.registration.google.client-id=dummy-id
spring.security.oauth2.client.registration.google.client-secret=dummy-secret

# JWT for tests
app.jwt.secret=9a4f4e3545645645645645645645645645645645645645645645645645645645
